## Peter Hauck - Alacritty Shell Setup for WSL on Windows
[terminal]
shell = "wsl.exe ~ -e bash"

[window]
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true 
decorations_theme_variant = "None"
decorations = "Full"
opacity = 0.98
blur = true 

[font]
normal = {family = "JetBrainsMono NF", style = "Regular"}

[colors]
primary.background = "#000000"
primary.foreground = "#c5c8c6"

[cursor]
style = "Block"

[keyboard]
bindings = [
{ key = "Paste",   mods = "Control", action = "Paste" },
{ key = "Copy",    mods = "Control", action = "Copy" },
{ key = "V",       mods = "Control", action = "Paste" },
{ key = "C",    mods = "Control", action = "Copy" }
]

[mouse]
bindings = [
{ mouse = "Right", action = "Paste" }
]

[scrolling]
history = 10000

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true
